### PR TITLE
fix: Added textarea ref and Auto-focus to textarea

### LINKED ISSUE #1736: If I start new chat, the focus is not on the text input window
It should be, so I click "Start chat" and immediately could start typing the message.

### PR DESCRIPTION
**Pull request by veeradyani222**
This PR ensures the chat input remains focused after message submission and when a response finishes streaming as well as initial chat load.

The textarea is focused immediately after a message is sent and a chat is loaded

Focus is restored when the chat status returns to ready

Users can continue typing without any extra clicks

/claim #1692
/fixes #1736

### CODE REVIEW

**Comment by veeradyani222** [comment]
@iskhakov Please Review this too :) As this is close to the other issue

File: platform/frontend/src/app/chat/page.tsx [hunk 1]
```diff
@@ -335,6 +336,16 @@ export default function ChatPage() {
     messages,
   ]);
 
+  // Auto-focus textarea when status becomes ready (message sent or stream finished)
+  useEffect(() => {
+    if (status === "ready" && textareaRef.current) {
+      // Use requestAnimationFrame for more reliable focusing
+      requestAnimationFrame(() => {
```
Comment (ashlkv) [inline platform/frontend/src/app/chat/page.tsx]: `requestAnimationFrame` seems like a workaround because there aren't any animation. Perhaps `useLayoutEffect` can be helpful. Same for the `requestAnimationFrame` below in code.

Comment (veeradyani222) [reply platform/frontend/src/app/chat/page.tsx]: Hi Anna! Addressed, have a look
