### PR TITLE
fix: revert organization logo preview when upload fails

### LINKED ISSUE #2559: Logo preview not reverted when upload fails
When changing the organization logo, if the upload fails, the preview continues to show the newly selected image instead of reverting to the original logo or empty state, which can mislead the user into thinking the change was saved.

#### Steps to Reproduce

1. Navigate to **Settings → Appearance**
2. Ensure an organization logo is already uploaded
3. Click **Change** and select a new valid PNG file
4. Allow the logo upload to fail for any reason
5. Observe the logo preview after the failure

[https://github.com/user-attachments/assets/5497fde6-e3de-434a-ba76-132cdfc7ee8e](https://github.com/user-attachments/assets/5497fde6-e3de-434a-ba76-132cdfc7ee8e)

### PR DESCRIPTION
**Pull request by abhinav-m22**
- Fixes #2559

Fixes an issue where the organization logo preview persisted even after a failed upload. Added error handling to revert the UI state when the upload mutation returns null.

[Screencast from 2026-02-09 17-57-45.webm](https://github.com/user-attachments/assets/8be950c9-730b-406b-b206-c745dfbfa486)

### CODE REVIEW

**Comment by London-Cat** [comment]
## 📊 Reputation Summary

| User | Rep | Pull Requests | Activity | Assigned | Core Reactions |
|------|-----|---------------|----------|----------|----------------|
| **abhinav-m22** | ⚡ 194 | [7✅](https://github.com/archestra-ai/archestra/pulls?q=is%3Apr%20author%3Aabhinav-m22%20is%3Amerged) [3🔄](https://github.com/archestra-ai/archestra/pulls?q=is%3Apr%20author%3Aabhinav-m22%20is%3Aopen) [2❌](https://github.com/archestra-ai/archestra/pulls?q=is%3Apr%20author%3Aabhinav-m22%20is%3Aclosed%20is%3Aunmerged) | [13 issues](https://github.com/archestra-ai/archestra/issues?q=is%3Aissue%20author%3Aabhinav-m22), 41 comments | [2](https://github.com/archestra-ai/archestra/issues?q=is%3Aissue%20state%3Aopen%20assignee%3Aabhinav-m22) | — |

---
_How is the score calculated? Read about it in the [Reputation Bot](https://github.com/archestra-ai/reputation-bot) repository_ 🤖

**Comment by abhinav-m22** [comment]
While testing, I found two minor issues with the logo removal flow:
1. **Incorrect Success Message:** Removing the logo displayed "Logo uploaded successfully".
2. **Incorrect Error Message:** Failing to remove the logo displayed "Failed to upload logo".

https://github.com/user-attachments/assets/44ba8dd7-839e-4e76-8222-eca2016b5d44

https://github.com/user-attachments/assets/dafdf011-426e-49d6-974b-af62824015b3

I have resolved these by implementing a dedicated mutation for removal with correct messaging and error handling.

| Screenshot 1 | Screenshot 2 |
|-------------|-------------|
| Screenshot from 2026-02-09 18-37-40 | Screenshot from 2026-02-09 18-37-51 |

File: platform/frontend/src/app/settings/appearance/_components/logo-upload.tsx [hunk 1]
```diff
@@ -51,9 +55,14 @@ export function LogoUpload({ currentLogo, onLogoChange }: LogoUploadProps) {
         setPreview(base64);
 
         try {
-          await uploadOrganizationLogoMutation.mutateAsync({
+          const result = await uploadOrganizationLogoMutation.mutateAsync({
             logo: base64,
           });
+
+          if (!result) {
+            throw new Error("Upload failed");
```
Comment (joeyorlando) [inline platform/frontend/src/app/settings/appearance/_components/logo-upload.tsx:63]: hmm, I'm not sure if we should `throw new Error` (here, or below as well) - this would crash the frontend, no?

Comment (abhinav-m22) [reply platform/frontend/src/app/settings/appearance/_components/logo-upload.tsx:63]: @joeyorlando This `throw new Error(...)` won’t crash anything here since it’s inside a try/catch and we handle it. We already use `throw new Error` in other parts of the repo too.
If you’d prefer, we can swap it to an early toast.error(...) + return and drop the throw.

Comment (joeyorlando) [reply platform/frontend/src/app/settings/appearance/_components/logo-upload.tsx:63]: ah sorry ignore my previous comment, I completely overlooked the `try/catch` 😄
