### PR TITLE
fix: errors when connecting Slack and GitHub connectors

### LINKED ISSUE #366: HTTP 500 when attempting to connect GitHub connector
https://github.com/user-attachments/assets/cdf33c1e-6dfe-4349-8fe8-0411f059495e

Image

I installed github mcp . then allow access of it (0Auth) but after successful authentication it is not redirecting to desktop app and failed to store the cred

### LINKED ISSUE #429: Browser auth for slack in the recent main
Environment variables with access tokens are not being passed to the container (but they are extracted correctly).

The particular MCP server, from the catalog, in question is https://github.com/archestra-ai/website/blob/main/app/app/mcp-catalog/data/mcp-evaluations/korotovsky__slack-mcp-server.json

### PR DESCRIPTION
**Pull request by joeyorlando**
Fixes #429

Fixes #366

### CODE REVIEW

File: desktop_app/src/backend/services/oauth-proxy-client.ts [hunk 1]
```diff
@@ -22,42 +24,32 @@ export interface OAuthProxyRequest {
   [key: string]: any;
 }
 
-export class OAuthProxyClient {
-  private baseUrl: string;
-
-  constructor(baseUrl?: string) {
-    this.baseUrl = baseUrl || process.env.OAUTH_PROXY_URL || 'https://oauth.dev.archestra.ai/oauth/callback';
```
Comment (joeyorlando) [inline desktop_app/src/backend/services/oauth-proxy-client.ts:29]: this baseUrl was incorrect

File: desktop_app/src/backend/services/oauth-proxy-client.ts [hunk 2]
```diff
@@ -126,86 +114,6 @@ export class OAuthProxyClient {
...
-        return [];
-      }
-
-      const data = await response.json();
-      return data.allowedDestinations || [];
-    } catch (error) {
-      log.warn(`Failed to get allowed destinations from oauth-proxy:`, error);
-      return [];
-    }
-  }
```
Comment (joeyorlando) [inline desktop_app/src/backend/services/oauth-proxy-client.ts:207]: not used anywhere

File: desktop_app/src/main-browser-auth.ts [hunk 3]
```diff
@@ -40,15 +40,6 @@ export function setupProviderBrowserAuthHandlers() {
...
   });
 
-  // Legacy support for Slack (backward compatibility)
-  ipcMain.handle('slack-auth', async () => {
-    const provider = getBrowserAuthProvider('slack-browser');
-    if (!provider.browserAuthConfig?.enabled) {
-      throw new Error('Browser auth not enabled for Slack');
-    }
-    return handleBrowserAuth(provider);
-  });
```
Comment (joeyorlando) [inline desktop_app/src/main-browser-auth.ts:50]: not used

File: desktop_app/src/backend/server/plugins/browser-auth/providers/slack-browser.ts
Comment (joeyorlando) [inline desktop_app/src/backend/server/plugins/browser-auth/providers/slack-browser.ts:1]: for the "browser auth" I wanted to use Google SSO, without these changes it wouldn't let me
